
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: studyingplatform
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5332/studyingplatform
    username: amigoscode
    password: password
    driverClassName: org.postgresql.Driver
file:
  upload-dir: videos
server:
  port: 8081